<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ot_cms"
 *
 * Auto generated by Extension Builder 2015-01-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Opentalent Migration Typo 8',
	'description' => 'Migrate from typo 6 to 8',
	'category' => 'plugin',
	'author' => 'Hupin Sébastien',
	'author_email' => 'sebastien.hupin@2iopenservice.fr',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '8.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.99.99',
			'beuser' => '8.99.99',
                        'ot_cms' => '1.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);