<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "theme_gallery"
 *
 * Auto generated by Extension Builder 2014-11-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Theme Gallery',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Hupin Sébastien',
	'author_email' => 'sebastien.hupin@laposte.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => 'fileadmin/theme_gallery',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-8.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);